# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - films-ratings-yulia-docker

on:
  push:
    branches:
      - lab_2
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://yuliacontainerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0a42fae75c9341878a05d36c29beda6c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4337581f0f9e417288ce2a31ad820dc1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: yuliacontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0a42fae75c9341878a05d36c29beda6c }}/yuliacontainerregistry:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'films-ratings-yulia-docker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7328544f8a114f2b962e44a41ed836b8 }}
        images: 'yuliacontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0a42fae75c9341878a05d36c29beda6c }}/yuliacontainerregistry:${{ github.sha }}'