# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - films-ratings-yulia-container

on:
  push:
    branches:
      - lab_2
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://yuliacontainerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a4b3223494e94ca59feb0185193d9936 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_18de187b66b34cad8b24cc4b076f2156 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: yuliacontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a4b3223494e94ca59feb0185193d9936 }}/cloudlab2image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'films-ratings-yulia-container'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e2233b2c1e2d46b0aa04539f2f3beaaf }}
        images: 'yuliacontainerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a4b3223494e94ca59feb0185193d9936 }}/cloudlab2image:${{ github.sha }}'